### ISSUE TITLE
Saving timeseries data as csv vs. xlsx

### ISSUE THREAD

**Issue by danielhuppmann** [ecemf/model_comparison#13]
Looking at the file **model_comparison.Rmd**, I'm confused why you query the data, then save it to disk as xlsx, then re-load it using pandas, and then export to csv...

```python
...
df.to_excel("./data/" + filename + ".xlsx")

import pandas as pd

read_file = pd.read_excel("./data/" + filename + ".xlsx", sheet_name="data")
read_file.to_csv("./data/" + filename + ".csv", index = None, header=True)
```

If you just want to write the timeseries data to a csv file, you can do that directly.

```python
df.data.to_csv("./data/" + filename + ".csv", index = None, header=True)
```

Also, note that saving as csv removes the **meta** attribute, which has relevant information like the version number - that can be helpful when trying to understand why plots look different from one day to the next.

**Comment by Renato-Rodrigues** [comment]
At the time the original code was created the csv file created with the df.data.to_csv method had substantial additional file size.
I never got into testing it further to checking why, or if the issue still remains. 
I will see if I find the time to check it again. 

Thk you for bringing this up.

**Comment by danielhuppmann** [comment]
The larger file size may be due to saving wide vs. long table format. Using `df.to_csv()` gives a wide dataframe whereas `df.data.to_csv()` is the long format.
